spring:
  main:
    web-application-type: reactive
  application:
    name: edge-service
  config:
    server:
      uri: http://localhost:8888
    import: 'optional:configserver:${spring.config.server.uri}'




